DROP TABLE IF EXISTS USER;
CREATE TABLE USER(USERNAME VARCHAR(255) PRIMARY KEY, PASSWORD VARCHAR(255), ROLE VARCHAR(255));
INSERT INTO USER VALUES('guest', 'password','guest');
INSERT INTO USER VALUES('admin', 'password','admin');
